config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users

  root 'home#index'

  resources :rooms do
    member do
      get :join
    end
  end
end

app/models/player.rb
class Player
	include Mongoid::Document
	include Mongoid::Timestamps

  belongs_to :user
  belongs_to :room

	field :role, type: String
	field :dead, type: Boolean
	field :inlove, type: String

	def dead?
		self.dead
	end

  # def admin?
  #   self.role == 'admin'
  # end
	#
  # def citizen?
  #   self.role == 'citizen'
  # end
	#
  # def werewolf?
  #   self.role == 'werewolf'
  # end
	#
  # def cupid?
  #   self.role == 'cupid'
  # end
	#
  # def girl?
  #   self.role =='girl'
  # end

  def set_role!(role)
    self.update_attribute(:role, role)
  end

	def self.roles
      %w(admin citizen warewolf cupid girl)
	end

  roles.each do |role|
    define_method("#{role}?") { self.role == role }
  end
end

app/models/room.rb
class Room
	include Mongoid::Document
	include Mongoid::Timestamps

	has_many :players
	belongs_to :user

	field :name, type: String
	field :status, type: String
	field :count, type: Integer

	scope :ready, -> { where(status: 'ready') }

	SEVEN_PLAYER_ROLE_MAP = ['werewolf', 'citizen', 'citizen', 'citizen', 'citizen', 'cupid', 'girl']

	def ready?
		self.status == 'ready'
	end

	def full?
		self.status == 'full'
	end

	def closed?
		self.status == 'closed'
	end

	def set_status!(status)
		self.update_attribute(:status, status)
  end

  def can_join?
  	check_fullness(self.players.count)
  	!full?
  end

  def check_fullness(count)
  	self.set_status!('full') if count >= 7
  end

  def assign_roles
  	shuffled = SEVEN_PLAYER_ROLE_MAP.shuffle
  	self.players.each_with_index do |player, index|
  		player.set_role!(shuffled[index])
  	end
  end

  
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :rooms
  has_many :players
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :username, type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]["$oid"])
      record if record && record.authenticatable_salt == salt
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  expose(:rooms) { Room.ready }


  def index
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  expose(:room, attributes: :room_params)
  expose(:room_player) { player_for_room }


  def new
  end

  def create
    room.user_id = current_user.id
    room.status = 'ready'
    if room.save
      redirect_to(room)
    else
      render :new
    end
  end

  def show

  end

  def join
    if room.can_join?
      Player.create(room_id: room.id, user_id: current_user.id)
      redirect_to(room)
    else
      flash[:alert] = "This room: #{room.name} is full"
      redirect_to root_path
    end
  end

  private

  def room_params
    params.require(:room).permit(:name, :status, :count)
  end

  def player_for_room
    current_user.players.where(room_id: room.id).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
= link_to 'Wal pokoik', new_room_path, class: 'btn btn-info'

- rooms.each do |room|
  %p
    = link_to "Join #{room.name}", join_room_path(room), class: 'btn btn-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wilkolaki
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} Wilkołaki
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Log in', new_user_session_path
    = yield

app/views/rooms/new.html.haml
= simple_form_for room do |f|
  = f.input :name
  = f.button :submit

app/views/rooms/show.html.haml
%h3
  YOU ARE IN ROOM
  = room.name

- unless room.user.id == current_user.id
  %div{class: "#{room_player.role}"}